---
- name: Build and Run Docker Image for Java App
  hosts: localhost
  become: true
  tasks:

    - name: Build Docker image
      community.docker.docker_image:
        name: jpetstoreapp_image
        tag: latest
        source: build
        build:
          path: "{{ playbook_dir }}"

    - name: Run Docker container
      community.docker.docker_container:
        name: jpetstoreapp_container
        image: jpetstoreapp_image:latest
        state: started
        ports:
          - "8080:8080"

